sonar.projectKey=Forge-Space_siza-gen
sonar.organization=forge-space
sonar.projectName=siza-gen

sonar.sources=src
sonar.tests=src/__tests__
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts

sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.test.ts,**/*.spec.ts
sonar.cpd.exclusions=src/registry/component-registry/**/*.ts,src/component-libraries/**/templates.ts,**/*.test.ts,**/*.spec.ts
