import { BaseGenerator, ComponentLibrary } from './base-generator.js';
import type { IGeneratedFile, IDesignContext, Architecture, StateManagement, Framework } from '../types.js';
import { createLogger } from '../logger.js';

const _logger = createLogger('vue-generator');

/**
 * Vue Generator - Generates Vue components and projects
 */
export class VueGenerator extends BaseGenerator {
  constructor(framework: Framework) {
    super(framework);
  }

  generateProject(
    projectName: string,
    _architecture: Architecture,
    stateManagement: StateManagement,
    designContext: IDesignContext
  ): IGeneratedFile[] {
    this.logStart('project', projectName);

    const files: IGeneratedFile[] = [];

    const deps: Record<string, string> = {
      vue: '^3.5.0',
      'vue-router': '^4.4.0',
    };
    if (stateManagement === 'pinia' || stateManagement !== 'none') {
      deps.pinia = '^2.2.0';
    }
    const devDeps: Record<string, string> = {
      '@vitejs/plugin-vue': '^5.2.0',
      'vue-tsc': '^2.1.0',
      vite: '^6.0.0',
      tailwindcss: '^4.0.0',
      autoprefixer: '^10.4.0',
      postcss: '^8.4.0',
      vitest: '^2.1.0',
      '@vue/test-utils': '^2.4.0',
    };
    files.push({
      path: 'package.json',
      content: this.createPackageJson(projectName, deps, devDeps),
    });

    files.push({
      path: 'tsconfig.json',
      content: JSON.stringify(
        {
          compilerOptions: {
            target: 'ES2020',
            module: 'ESNext',
            moduleResolution: 'bundler',
            strict: true,
            jsx: 'preserve',
            resolveJsonModule: true,
            isolatedModules: true,
            noEmit: true,
            lib: ['ES2020', 'DOM', 'DOM.Iterable'],
            skipLibCheck: true,
            paths: { '@/*': ['./src/*'] },
          },
          include: ['src/**/*.ts', 'src/**/*.vue'],
        },
        null,
        2
      ),
    });

    files.push({
      path: 'vite.config.ts',
      content: `import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import { resolve } from 'node:path';

export default defineConfig({
  plugins: [vue()],
  resolve: { alias: { '@': resolve(__dirname, 'src') } },
});
`,
    });

    const primary = designContext.colorPalette?.primary ?? '#3b82f6';
    files.push({
      path: 'tailwind.config.ts',
      content: `import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{vue,ts}'],
  theme: {
    extend: {
      colors: { primary: '${primary}' },
    },
  },
  plugins: [],
} satisfies Config;
`,
    });

    files.push({
      path: 'index.html',
      content: `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectName}</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>
`,
    });

    files.push({
      path: 'src/main.ts',
      content: `import { createApp } from 'vue';
import { createPinia } from 'pinia';
import { createRouter, createWebHistory } from 'vue-router';
import App from './App.vue';
import './style.css';

const router = createRouter({
  history: createWebHistory(),
  routes: [
    { path: '/', component: () => import('./views/HomeView.vue') },
  ],
});

const app = createApp(App);
app.use(createPinia());
app.use(router);
app.mount('#app');
`,
    });

    files.push({
      path: 'src/style.css',
      content: '@import "tailwindcss";\n',
    });

    files.push({
      path: 'src/App.vue',
      content: `<script setup lang="ts">
import { RouterView } from 'vue-router';
</script>

<template>
  <div class="min-h-screen bg-background text-foreground">
    <RouterView />
  </div>
</template>
`,
    });

    files.push({
      path: 'src/views/HomeView.vue',
      content: `<script setup lang="ts">
</script>

<template>
  <main class="mx-auto max-w-4xl px-4 py-12">
    <h1 class="text-3xl font-bold tracking-tight">
      ${projectName}
    </h1>
    <p class="mt-2 text-muted-foreground">
      Vue project scaffolded by Siza.
    </p>
  </main>
</template>
`,
    });

    files.push({
      path: 'README.md',
      content: `# ${projectName}\n\nVue 3 + TypeScript + Vite project generated by Siza.\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`,
    });

    this.logComplete('project', projectName, files.length);
    return files;
  }

  generateComponent(
    componentType: string,
    props: Record<string, unknown>,
    designContext: IDesignContext,
    componentLibrary?: ComponentLibrary
  ): IGeneratedFile[] {
    this.logStart('component', componentType);

    const componentName = this.formatComponentName(componentType);
    const files: IGeneratedFile[] = [];

    // Component file
    files.push(this.createComponentFile(componentName, componentType, props, designContext, componentLibrary));

    // Test file
    files.push(this.createTestFile(componentName, componentType, designContext, componentLibrary));

    this.logComplete('component', componentType, files.length);
    return files;
  }

  // Component Library Implementation Methods

  protected getShadcnDependencies(): string[] {
    return ['@radix-ui/vue-slot', 'class-variance-authority', 'clsx', 'tailwind-merge', 'lucide-vue-next'];
  }

  protected getRadixDependencies(): string[] {
    return [
      '@radix-ui/vue-slot',
      '@radix-ui/vue-dialog',
      '@radix-ui/vue-dropdown-menu',
      '@radix-ui/vue-select',
      '@radix-ui/vue-tabs',
    ];
  }

  protected getHeadlessUIDependencies(): string[] {
    return ['@headlessui/vue', '@heroicons/vue'];
  }

  protected getPrimeVueDependencies(): string[] {
    return ['primevue', 'primeicons'];
  }

  protected getMaterialDependencies(): string[] {
    return ['@mui/material', '@mui/icons-material'];
  }

  protected getShadcnImports(): string[] {
    return [
      'import { cn } from "@/lib/utils"',
      'import { Button } from "@/components/ui/button"',
      'import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"',
    ];
  }

  protected getRadixImports(): string[] {
    return [
      'import * as Dialog from "@radix-ui/vue-dialog"',
      'import * as DropdownMenu from "@radix-ui/vue-dropdown-menu"',
      'import * as Select from "@radix-ui/vue-select"',
      'import * as Tabs from "@radix-ui/vue-tabs"',
    ];
  }

  protected getHeadlessUIImports(): string[] {
    return [
      'import { Button } from "@headlessui/vue"',
      'import { Dialog } from "@headlessui/vue"',
      'import { Menu } from "@headlessui/vue"',
    ];
  }

  protected getPrimeVueImports(): string[] {
    return [
      'import Button from "primevue/button"',
      'import Dialog from "primevue/dialog"',
      'import InputText from "primevue/inputtext"',
      'import DataTable from "primevue/datatable"',
    ];
  }

  protected getMaterialImports(): string[] {
    return [
      'import { Button } from "@mui/material/Button"',
      'import { Dialog } from "@mui/material/Dialog"',
      'import { TextField } from "@mui/material/TextField"',
      'import { Card } from "@mui/material/Card"',
    ];
  }

  protected generateShadcnComponent(componentType: string, _props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `<template>
  <Card :class="cn('w-full max-w-md', props.className)">
    <CardHeader>
      <CardTitle>${componentName}</CardTitle>
      <CardDescription>
        A ${componentType.toLowerCase()} component built with shadcn/ui
      </CardDescription>
    </CardHeader>
    <CardContent>
      <p>This is a ${componentType.toLowerCase()} component using shadcn/ui design system.</p>
      <Button class="mt-4">Click me</Button>
    </CardContent>
  </Card>
</template>

<script setup lang="ts">
import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"

interface Props {
  className?: string
}

const props = withDefaults(defineProps<Props>(), {
  className: ''
})
</script>`;
  }

  protected generateRadixComponent(componentType: string, _props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `<template>
  <Dialog.Root>
    <Dialog.Trigger as-child>
      <button>${componentName}</button>
    </Dialog.Trigger>
    <Dialog.Portal>
      <Dialog.Overlay class="fixed inset-0 bg-black/50" />
      <Dialog.Content class="fixed left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 bg-card p-6 rounded-lg shadow-lg border">
        <Dialog.Title>${componentName}</Dialog.Title>
        <Dialog.Description>
          A ${componentType.toLowerCase()} component using Radix UI primitives
        </Dialog.Description>
        <DropdownMenu.Root>
          <DropdownMenu.Trigger as-child>
            <button>Options</button>
          </DropdownMenu.Trigger>
          <DropdownMenu.Portal>
            <DropdownMenu.Content class="bg-white p-2 rounded-lg shadow-lg">
              <DropdownMenu.Item>Option 1</DropdownMenu.Item>
              <DropdownMenu.Item>Option 2</DropdownMenu.Item>
            </DropdownMenu.Content>
          </DropdownMenu.Portal>
        </DropdownMenu.Root>
      </Dialog.Content>
    </Dialog.Portal>
  </Dialog.Root>
</template>

<script setup lang="ts">
import * as Dialog from "@radix-ui/vue-dialog"
import * as DropdownMenu from "@radix-ui/vue-dropdown-menu"
</script>`;
  }

  protected generateHeadlessUIComponent(componentType: string, _props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `<template>
  <div class="p-4">
    <Button @click="handleClick">${componentName}</Button>
    <Dialog :open="open" @close="handleClose">
      <Dialog.Panel class="fixed inset-0 bg-card p-6 rounded-lg shadow-lg border">
        <Dialog.Title>${componentName}</Dialog.Title>
        <Dialog.Description>
          A ${componentType.toLowerCase()} component using Headless UI
        </Dialog.Description>
        <div class="mt-4">
          <Button @click="handleClose">Close</Button>
        </div>
      </Dialog.Panel>
    </Dialog>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { Button } from "@headlessui/vue"
import { Dialog } from "@headlessui/vue"

const open = ref(false)

const handleClick = () => {
  open.value = true
}

const handleClose = () => {
  open.value = false
}
</script>`;
  }

  protected generatePrimeVueComponent(componentType: string, _props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `<template>
  <div class="p-4">
    <Button :label="${componentName}" @click="handleClick" />
    <Dialog v-model:visible="visible" modal header="${componentName}">
      <p class="mb-4">A ${componentType.toLowerCase()} component using PrimeVue</p>
      <Button label="Close" @click="visible = false" />
    </Dialog>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import Button from 'primevue/button'
import Dialog from 'primevue/dialog'

const visible = ref(false)

const handleClick = () => {
  visible.value = true
}
</script>`;
  }

  protected generateMaterialComponent(componentType: string, _props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `<template>
  <div class="p-4">
    <Button variant="contained" @click="handleClick">
      ${componentName}
    </Button>
    <Dialog v-model="open" @update:model-value="handleClose">
      <DialogTitle>${componentName}</DialogTitle>
      <DialogContent>
        <p>A ${componentType.toLowerCase()} component using Material UI</p>
      </DialogContent>
      <DialogActions>
        <Button @click="handleClose">Close</Button>
      </DialogActions>
    </Dialog>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { Button } from "@mui/material/Button"
import { Dialog, DialogTitle, DialogContent, DialogActions } from "@mui/material/Dialog"

const open = ref(false)

const handleClick = () => {
  open.value = true
}

const handleClose = () => {
  open.value = false
}
</script>`;
  }

  protected generateTailwindComponent(componentType: string, _props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `<template>
  <div class="p-4 bg-white rounded-lg shadow-md">
    <h2 class="text-xl font-bold mb-4">${componentName}</h2>
    <p class="text-muted-foreground mb-4">
      A ${componentType.toLowerCase()} component using Tailwind CSS
    </p>
    <button
      class="bg-primary text-primary-foreground hover:bg-primary/90 px-4 py-2 rounded"
      @click="handleClick"
    >
      Click me
    </button>
  </div>
</template>

<script setup lang="ts">
const handleClick = () => {
  console.log('Button clicked')
}
</script>`;
  }

  private createComponentFile(
    componentName: string,
    componentType: string,
    props: Record<string, unknown>,
    designContext: IDesignContext,
    componentLibrary?: ComponentLibrary
  ): IGeneratedFile {
    let content: string;

    if (componentLibrary && componentLibrary !== 'none') {
      // Use component library-specific generation
      content = this.generateComponentLibraryCode(componentType, props, componentLibrary);
    } else {
      // Use default Tailwind CSS generation
      content = this.generateTailwindComponent(componentType, props);
    }

    return {
      path: `src/components/${componentName}.vue`,
      content,
    };
  }

  private createTestFile(
    componentName: string,
    componentType: string,
    _designContext: IDesignContext,
    _componentLibrary?: ComponentLibrary
  ): IGeneratedFile {
    const content = `import { mount } from '@vue/test-utils'
import { describe, it, expect } from 'vitest'
import ${componentName} from './${componentName}.vue'

describe('${componentName}', () => {
  it('renders without crashing', () => {
    const wrapper = mount(${componentName})
    expect(wrapper.exists()).toBe(true)
  })

  it('displays the component type', () => {
    const wrapper = mount(${componentName})
    expect(wrapper.text()).toMatch(/${componentType.toLowerCase()}/i)
  })
})
`;

    return {
      path: `src/components/${componentName}.test.ts`,
      content,
    };
  }
}
